# This is only the name of the workflow which will represent everything 
name: CICD

# Manual Clicks 
on:
  workflow_dispatch:

  jobs:
    code:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code 
          steps: echo" Code Clone from Github"
    build:
      runs-on: ubuntu-latest
      steps:
        
        - name: Build Docker Container
          steps: echo "Docker Container Build"
    test:
      runs-on: ubuntu-latest
      steps:
        - name: deploying the app 
          steps: echo "Testing the docker file"
          
