name: Hello Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello to users
        run: echo "Hello Dosto"

      - name: Say Hello to GitHub User
        run: echo "Hello ${{ github.actor }}"
  details:
    runs-on: ubuntu-latest
    steps:
      - name: Show what is the version of python , docker etc
        run: docker --version && python --version

  printing_gagan:
    runs-on: ubuntu-latest

    steps:
      - name: Say gagan to hi 
        run: echo "Hello Bahisahab"
